version: '3.8'
services:
  backend:
    build: ./back
    volumes:
      - type: volume
        source: file-storage
        target: /app/files
    ports:
      - 8000:8000
    environment:
      - API_URL=http://localhost:8000
      - ALLOWED_ORIGINS=http://localhost
      - UPLOAD_FOLDER=/app/files
  frontend:
    build:
      context : ./front
      args:
        - VITE_APP_API_URL=http://localhost:8000
    ports:
      - 80:80
volumes:
  file-storage:
