# Dockerfile
FROM node:18 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
ARG VITE_APP_API_URL
ENV VITE_APP_API_URL=$VITE_APP_API_URL

RUN npm run build

ENV NODE_ENV=production


FROM nginx:stable-alpine as production
COPY --from=build /app/dist /usr/share/nginx/html
